### ISSUE TITLE
In the utils.py file, neighbors_ From_ The delaunay() function does not consider the neighbor index of the last node, why is this?

### ISSUE THREAD

**Issue by belief33** [yakovlev31/graphpdes#1]
source code：

def neighbors_from_delaunay(tri):
    neighbors_tri = tri.vertex_neighbor_vertices
    neighbors = []
    for i in range(len(neighbors_tri[0])-1):
        curr_node_neighbors = []
        for j in range(neighbors_tri[0][i], neighbors_tri[0][i+1]):
            curr_node_neighbors.append(neighbors_tri[1][j])
        neighbors.append(curr_node_neighbors)
    return neighbors

**Comment by yakovlev31** [comment]
tri.vertex_neighbor_vertices returns (indptr, indices). Neighbors of node k are extracted as indices[indptr[k]:indptr[k+1]]. So neighbors_tri[0] is note node indices, its indptr. So we need to iterate only up to indptr[-1] (outer cycle) to get all the neighbors.
See here for more details: [https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.vertex_neighbor_vertices.html#scipy.spatial.Delaunay.vertex_neighbor_vertices](link)
